Hw5.2
ValentinaShvetsova/Homework pull request #10
Opened 2020-10-26 16:37 UTC by ValentinaShvetsova

2020-11-13 13:07 UTC, yurii-litvinov requested changes
Нету тестов на собственно баланс скобок

2020-11-13 13:07 UTC, yurii-litvinov commented on Homework5/BracketsBalance.c
> +
После "{" пустая строка не ставится обычно

2020-11-13 13:07 UTC, yurii-litvinov commented on Homework5/BracketsBalance.c
> +			break;
Эти три случая тоже можно объединить, чтобы не было копипаста. Подумайте, как

2020-11-13 13:07 UTC, yurii-litvinov commented on Homework5/Stack/Main.c
> +bool test1() {
Не лучшие имена тестов. Тесты надо именовать так, чтобы было понятно, что именно они проверяют

2020-11-13 13:07 UTC, yurii-litvinov commented on Homework5/Stack/Main.c
> +	return(isEmpty(stack));
Тут скобки лишние, return не функция

2020-11-13 13:07 UTC, yurii-litvinov commented on Homework5/Stack/Main.c
> +}
Ве тесты проходит стек, который просто запоминает последнее запушенное в него число. Нету теста, который бы проверил, что стек --- это стек

2020-11-13 13:07 UTC, yurii-litvinov commented on Homework5/Stack/Stack.h
> +struct Stack* createStack();
Надо комментарии к каждой функции каждого заголовочного файла

2020-11-23 14:33 UTC, yurii-litvinov requested changes
Надо ещё разрешить конфликт с мастером (видимо, стек откуда-то вмерджили и тут поправили, вот они и разошлись). И "Нету тестов на собственно баланс скобок" не поправлено, тестов как не было, так и нет.

2020-11-23 14:33 UTC, yurii-litvinov commented on Homework5/BracketsBalance.c
> +			else if ((string[i] == ')' && pop(stack) != '(') || (string[i] == '}' && pop(stack) != '{') || (string[i] == ']' && pop(stack) != '['))
Это очень-очень стрёмно, потому что pop имеет побочный эффект, так что _иногда_ оно будет снимать аж три скобки со стека. Надо сначала сделать pop, потом посмотреть в if-е, совпал ли результат с ожиданием.

2020-11-23 14:33 UTC, yurii-litvinov commented on Homework5/Stack/Source.c
> +struct StackElement {
Структуры лучше объявлять все вместе до всех функций, чтобы их потом не искать по всему файлу

2020-11-23 14:33 UTC, yurii-litvinov commented on Homework5/Stack/Stack.h
> +//This function create stack
Тут комментарии тоже стоит поправить

2020-12-01 15:19 UTC, ValentinaShvetsova commented on Homework5/BracketsBalance.c
> +			else if ((string[i] == ')' && pop(stack) != '(') || (string[i] == '}' && pop(stack) != '{') || (string[i] == ']' && pop(stack) != '['))
А можно ли прямо из гита решить конфликт?

2020-12-08 07:55 UTC, yurii-litvinov approved these changes
Тестов всё равно нету, но ладно :)

2020-12-08 07:55 UTC, yurii-litvinov commented on Homework5/Stack/Stack.h
> +//This function create stack
creates правильнее

2020-12-08 13:12 UTC, merged