Hw5.1
ValentinaShvetsova/Homework pull request #11
Opened 2020-10-27 19:02 UTC by ValentinaShvetsova

2020-11-14 15:34 UTC, yurii-litvinov requested changes

2020-11-14 15:34 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +bool calculationPermission(char postfixExpression[]) {
Permission --- это "разрешение" в смысле "разрешить что-нибудь сделать". Тут, наверное, лучше "Solution", но поскольку функции должны называться глаголом, то "calculate" или "solve" или что-то такое.

2020-11-14 15:34 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +		if (postfixExpression[i] - '0' >= 0 && postfixExpression[i] - '0' < 10)
Можно было просто `if (postfixExpression[i] >= '0' && postfixExpression[i] <= '9')`

2020-11-14 15:34 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +					return false;
Так утечка памяти будет, стек-то никто не удалит

2020-11-14 15:34 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +					push(stack, firstElement);
Чтобы так не мучиться, можно было сделать функцию top, которая бы возвращала значение в голове, саму голову не меняя, и использовать тут size, чтобы понять, хватает ли нам аргументов

2020-11-14 15:34 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +	bool resultExictence = false;
"resultExi**s**tence", и лучше булевые переменные называть вопросом, типа "resultExists"

2020-11-14 15:34 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +	printf("%d ", result);
Не-не, а как это тестировать или использовать калькулятор в случае, когда на консоль выводить ничего не надо (например, как часть компилятора, для вычисления константных выражений)? Давайте весь ввод-вывод будет только в main-е или специально предназначенных для этого функциях, а остальные даже не будут знать про существование консоли.

2020-11-14 15:34 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +}
Пустой строки между функциями не хватает

2020-11-14 15:34 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +}
Только негативные тесты? Я могу легко их пройти, просто возвращая false всегда.

2020-11-14 15:34 UTC, yurii-litvinov commented on Homework5/Stack/Main.c
> +bool test1() {
Имена тестов не очень

2020-11-23 14:23 UTC, yurii-litvinov requested changes

2020-11-23 14:23 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +#include <stdio.h>
Вообще, то, что PostfixCalculator.c лежит в Homework5, намекает, что и все остальные исходники остальных задач из Homework5 будут лежать тут, что пугает. Лучше каждую задачу всё-таки в отдельую папку

2020-11-23 14:23 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +	return;
Этот return не нужен

2020-11-23 14:23 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +void getResult(struct Stack* stack, int* result) {
Я бы сделал `int getResult(struct Stack* stack)`

2020-11-23 14:23 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +bool calculationSolution(char postfixExpression[], int *result) {
"поскольку функции должны называться глаголом, то "calculate" или "solve" или что-то такое." :)

2020-11-23 14:23 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +		if (postfixExpression[i] >= '0' && postfixExpression[i] < '10')
Не, < '10' работать не будет (точнее будет, но не так, как Вы хотите), потому что нет символа '10'. Надо именно <= '9'

2020-11-23 14:23 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +
Лишняя пустая строчка.

2020-11-23 14:23 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +		{
Скобки неконсистентны :)

2020-11-23 14:23 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +		int resulting = pop(stack);
const

2020-11-23 14:23 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +		if (isEmpty(stack)){
Пробела перед { не хватает

2020-11-23 14:23 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +			push(stack, resulting);
А идея с функцией top Вам совсем-совсем не понравилась? Просто это как-то выглядит _неловко_ :)

2020-11-23 14:23 UTC, yurii-litvinov commented on Homework5/Stack/Source.c
> +void deleteStack(struct StackElement**head) {
Пробела не хватает

2020-11-23 14:23 UTC, yurii-litvinov commented on Homework5/Stack/Main.c
> +bool test1() {
Имена тестов всё ещё не очень

2020-12-01 17:08 UTC, ValentinaShvetsova commented on Homework5/PostfixCalculator.c
> +#include <stdio.h>
Вообще, у меня возникли определенные трудности с их перемещением уже после коммитов, поэтому я хотела после перемещения ветки в мастер их переместить

2020-12-01 17:11 UTC, ValentinaShvetsova commented on Homework5/PostfixCalculator.c
> +void getResult(struct Stack* stack, int* result) {
Мне нужно, чтобы result изменялся не только в функции

2020-12-01 17:16 UTC, ValentinaShvetsova commented on Homework5/PostfixCalculator.c
> +			push(stack, resulting);
Не то, чтобы эту функцию было сложно написать, просто я пока не вижу разницы между тем и другим вариантом

2020-12-01 17:20 UTC, ValentinaShvetsova commented on Homework5/Stack/Source.c
> +void deleteStack(struct StackElement**head) {
Между названием функции и её аргументами?

2020-12-08 07:58 UTC, yurii-litvinov commented on Homework5/Stack/Source.c
> +void deleteStack(struct StackElement**head) {
Не-а, после звёздочек. Вопросы лучше в Телеграм, потому что GitHub шлёт кучу нотификаций, и вопрос невозможно заметить

2020-12-08 08:00 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +void getResult(struct Stack* stack, int* result) {
Ну так да, вернули его из функции и присвоили куда нужно. Смотрите
```c
  int result = 0;
  <делаем что-то с result>
  getResult(stack, &result);
```
--- это то же самое, что после предлагаемого преобразования
```c
  int result = 0;
  <делаем что-то с result>
  result = getResult(stack);
```

2020-12-08 08:11 UTC, yurii-litvinov requested changes

2020-12-08 08:11 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +#include <stdio.h>
Ну ладно

2020-12-08 08:11 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +		if (isEmpty(stack)){
Не поправлено

2020-12-08 08:11 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +		int resulting = pop(stack);
Не поправлено

2020-12-08 08:11 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +					push(stack, firstElement);
Наверное, было бы красивее
```c
if (!isEmpty(stack)) {
    if (!isEmpty(stack) && !(postfixExpression[i] == '/' && top(stack) == 0)) {
        performOperation(postfixExpression[i], stack);
    }
}
```

2020-12-08 08:11 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +			push(stack, resulting);
Ну тут да, тут бы Вам помогла функция size или что-то такое

2020-12-08 08:11 UTC, yurii-litvinov commented on Homework5/Stack/Source.c
> +#include "Stack.h"
Этот файл, наверное, должен был называться Stack.c

2020-12-08 08:11 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +	if (calculationSolution(string1, &result1) || calculationSolution(string2, &result2) || calculationSolution(string3, &result3)) {
Есть только calculateSolution, не компилируется. И куча предупреждений компилятора

2020-12-25 13:05 UTC, yurii-litvinov requested changes
Удалили старый стек и забыли выложить новый, не работает :)

2020-12-25 13:05 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +				if (!isEmpty(stack) && !(postfixExpression[i] == '/' && firstElement == 0)) {
Тут уже понятно, что он !isEmpty, top ведь не меняет стека

2020-12-25 13:05 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +		if (isEmpty(stack)) {
И тут всё-таки надо было pop делать, иначе стек не пуст и ответ будет неправильным

2020-12-25 13:05 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +	if (!isEmpty(stack)){
Пробела не хватает :)

2020-12-27 19:14 UTC, yurii-litvinov approved these changes
Окей, зачтена

2020-12-27 19:14 UTC, yurii-litvinov commented on Homework5/PostfixCalculator.c
> +	if (!isEmpty(stack)){
Так и не хватает

2020-12-27 19:14 UTC, yurii-litvinov commented on Homework5/Stack/Stack.c
> +		return element;
Да просто return stack->head->element;

2020-12-27 19:14 UTC, yurii-litvinov commented on Homework5/Stack/Stack.c
> +	return NULL;
return '\0';, это ж функция, возвращающая char

2021-05-21 15:57 UTC, closed without merging