Hw5.3
ValentinaShvetsova/Homework pull request #12
Opened 2020-11-01 20:34 UTC by ValentinaShvetsova

2020-11-15 10:55 UTC, yurii-litvinov requested changes

2020-11-15 10:55 UTC, yurii-litvinov commented on Homework5/SortingStation.c
> +void convertToPostfix(char infixExpression[], char postfixExpression[]) {
Фигурные скобки в разных стилях, выше была на отдельной строке, тут на той же

2020-11-15 10:55 UTC, yurii-litvinov commented on Homework5/SortingStation.c
> +}
А тут надо пустую строку между функциями

2020-11-15 10:55 UTC, yurii-litvinov commented on Homework5/SortingStation.c
> +	struct Stack* stack = createStack();
Вообще, createStack() запросто может вернуть NULL

2020-11-15 10:55 UTC, yurii-litvinov commented on Homework5/SortingStation.c
> +		if (infixExpression[i] >= '0' && infixExpression[i] <= '9') {
Есть библиотечная функция isdigit, кстати

2020-11-15 10:55 UTC, yurii-litvinov commented on Homework5/SortingStation.c
> +					push(stack, topOperation);
Так сделали бы стеку функцию top

2020-11-15 10:55 UTC, yurii-litvinov commented on Homework5/Stack/Main.c
> +}
Тут тоже тесты надо обновить (имена и сожержание, они не проверяют, что стек --- это стек)

2020-11-15 10:55 UTC, yurii-litvinov commented on Homework5/Stack/Source.c
> +#include "Stack.h"
Наверное, файл должен был называться Stack.c а не Source.c

2020-11-15 10:55 UTC, yurii-litvinov commented on Homework5/Stack/Source.c
> +	}
И надо сам стек ещё удалить, иначе утечка памяти

2020-11-15 10:55 UTC, yurii-litvinov commented on Homework5/Stack/Source.c
> +void deleteStack(struct Stack** head) {
Неправда, тут он уже не head, а стек целиком :)

2020-11-23 17:27 UTC, yurii-litvinov requested changes
Надо ещё чуть доправить

2020-11-23 17:27 UTC, yurii-litvinov commented on Homework5/SortingStation.c
> +		char operation = pop(stack);
const :)

2020-11-23 17:27 UTC, yurii-litvinov commented on Homework5/SortingStation.c
> +	if (!tests) {
тесты не вызываются, () не хватает

2020-11-23 17:27 UTC, yurii-litvinov commented on Homework5/SortingStation.c
> +		if (infixExpression[i] >= '0' && infixExpression[i] <= '9') {
Если замечание к пуллреквесту есть, надо на него как-то отреагировать --- поправить или написать, что править не хотите (это тоже вполне допустимо, особенно если объяснить, почему). Если просто оставить без внимания, все подумают, что Вы его просто не заметили.

2020-11-23 17:27 UTC, yurii-litvinov commented on Homework5/Stack/Main.c
> +}
Имена ок, но теста, который бы не прошла структура данных, просто запоминающая последнее переданное ей значение, всё так же нет. К тестам стоит относиться как к игре --- если я могу написать код, который не стек, но пройдёт все Ваши тесты, Вы проиграли :)

2020-12-01 17:25 UTC, ValentinaShvetsova commented on Homework5/SortingStation.c
> +					push(stack, topOperation);
Да, я увидела комментарий, он просто очень похож на комментарий из 5.1, так что я подумала, что дублировать его нет смысла

2020-12-01 17:26 UTC, ValentinaShvetsova commented on Homework5/Stack/Main.c
> +}
Мне кажется я поняла какой тест сделать, спасибо

2020-12-01 17:29 UTC, ValentinaShvetsova commented on Homework5/Stack/Main.c
> +}
Если пока стек не пустой, я возвращаю значение функцией pop() и сверяю это значение с верным, то такой тест докажет, что стек - это стек?

2020-12-08 10:59 UTC, yurii-litvinov commented on Homework5/Stack/Main.c
> +}
Нет :) Я же могу стек сделать просто одной переменной, push будет запоминать в этой переменной значение, pop возвращать это значение. Тогда тест с одним push и pop пройдёт, хотя это не стек

2020-12-08 11:07 UTC, yurii-litvinov approved these changes
Ну так, половину замечаний поправили. Но ладно :)

2020-12-08 11:07 UTC, yurii-litvinov commented on Homework5/SortingStation.c
> +		if (infixExpression[i] >= '0' && infixExpression[i] <= '9') {
:(

2020-12-08 11:07 UTC, yurii-litvinov commented on Homework5/SortingStation.c
> +					push(stack, topOperation);
Ну здесь бы это точно сделало код красивее. Не надо было бы этот push делать и даже topOperation заводить

2021-05-21 15:57 UTC, closed without merging