New solution added, but it doesn't work, because tail isn't pointing …
ValentinaShvetsova/Homework pull request #13
Opened 2020-11-02 19:21 UTC by ValentinaShvetsova

…on head of list

2020-11-15 11:26 UTC, yurii-litvinov requested changes
Почти всё правильно (и, кстати, весьма технично), надо только поправить небольшие баги.

2020-11-15 11:26 UTC, yurii-litvinov commented on Homework6/Countdown/Countdown/CircleList.c
> +	return list->head->value;
Если предположить, что оно существует

2020-11-15 11:26 UTC, yurii-litvinov commented on Homework6/Countdown/Countdown/CircleList.h
> +struct List* createList();
Тоже нужен комментарий

2020-11-15 11:26 UTC, yurii-litvinov commented on Homework6/Countdown/Countdown/CircleList.h
> +//This function check whether the list empty or not
Комментарий от // отделяется пробелом

2020-11-15 11:26 UTC, yurii-litvinov commented on Homework6/Countdown/Countdown/CircleList.h
> +//This function delete value from list
Не только. Ещё и сдвигает голову на следующий за удалённым элемент, это тоже надо отразить в комментарии

2020-11-15 11:26 UTC, yurii-litvinov commented on Homework6/Countdown/Countdown/CircleList.c
> +	list->head = current->next;
Если мы хотим удалить последний элемент, можем оказаться в неприятной ситуации

2020-11-15 11:26 UTC, yurii-litvinov commented on Homework6/Countdown/Countdown/Countdown.c
> +	deleteValue(list, 1);
Надо ещё сам список удалить

2020-11-15 17:57 UTC, ValentinaShvetsova commented on Homework6/Countdown/Countdown/CircleList.c
> +	return list->head->value;
В main происходит удаление до последнего элемента, то есть оно обязано существовать. Или я что-то не так поняла?

2020-11-15 18:06 UTC, ValentinaShvetsova commented on Homework6/Countdown/Countdown/CircleList.c
> +	list->head = current->next;
Но ведь здесь просто list->head и list->tail станут NULL и ничего плохого вроде бы не произойдёт.

2020-11-15 18:39 UTC, yurii-litvinov commented on Homework6/Countdown/Countdown/CircleList.c
> +	return list->head->value;
Если модуль циклического списка будет использоваться только с этим main и только так, как Вы думаете, то да, всё ок. Но так не бывает. Это нарушение инкапсуляции "в другую сторону" --- модуль делает предположения о том, как его будут использовать.

2020-11-15 18:40 UTC, yurii-litvinov commented on Homework6/Countdown/Countdown/CircleList.c
> +	list->head = current->next;
С чего бы им? current->next равен current, если всё правильно

2020-11-23 17:55 UTC, yurii-litvinov requested changes

2020-11-23 17:55 UTC, yurii-litvinov commented on Homework6/Countdown/Countdown/Countdown.c
> +	free(list);
А этого недостаточно. Потому что list вполне вправе сам выделять себе память под какие-то вспомогательные данные, а тут мы удаляем только саму структуру List, не давая списку навести за собой порядок. Надо deleteList или что-то такое вызывать.

2020-11-23 17:55 UTC, yurii-litvinov commented on Homework6/Countdown/Countdown/Countdown.c
> +
Лишняя пустая строчка :)

2020-11-23 17:55 UTC, yurii-litvinov commented on Homework6/Countdown/Countdown/CircleList.c
> +	list->head = current->next;
И не поправили, и не возразили. Так нельзя :)

2020-11-23 17:55 UTC, yurii-litvinov commented on Homework6/Countdown/Countdown/CircleList.c
> +	return list->head->value;
И тут

2020-12-01 17:44 UTC, ValentinaShvetsova commented on Homework6/Countdown/Countdown/Countdown.c
> +	free(list);
А если еще и удалять все структуры узла при его удалении?

2020-12-08 11:27 UTC, yurii-litvinov requested changes
Пока что лучше не стало. Ещё раз напоминаю, что вопросы лучше задавать напрямую, а не в комментариях на гитхабе, потому что пока я их прочитаю, будет уже поздно.

2020-12-08 11:27 UTC, yurii-litvinov commented on Homework6/Countdown/Countdown/CircleList.c
> +	if (current->next == NULL) {
Стоп, это ж циклический список, current->next никогда не NULL. У Вас всё работает просто потому, что в Считалочке в списке всегда остаётся один элемент, но я тут хотел, чтобы циклический список был достаточно универсальным. Чтобы его и в других задачах можно было использовать (вдруг на зачёте надо будет).

2020-12-08 11:27 UTC, yurii-litvinov commented on Homework6/Countdown/Countdown/Countdown.c
> +	free(list);
Конечно. Опять-таки, тут сам алгоритм решения гарантирует, что список к этому моменту пуст, но это не повод не делать функцию удаления списка вовсе.

2020-12-20 16:52 UTC, yurii-litvinov requested changes
Запустил, упало. На что Вы надеялись, когда сдавали? :)

2020-12-20 16:52 UTC, yurii-litvinov commented on Homework6/Countdown/Countdown/CircleList.c
> +	list->head = current->next;
Не исправлено

2020-12-20 16:52 UTC, yurii-litvinov commented on Homework6/Countdown/Countdown/CircleList.c
> +	free(list->head->value);
list->head->value --- это число, а не указатель. free опять неправильно используете.

2020-12-20 16:52 UTC, yurii-litvinov commented on Homework6/Countdown/Countdown/CircleList.c
> +	free(list->head);
К этому моменту list->head->next равно list->head, двойное удаление получится

2020-12-26 09:56 UTC, yurii-litvinov approved these changes

2020-12-26 09:56 UTC, yurii-litvinov commented on Homework6/Countdown/Countdown/CircleList.c
> +	list->head = current->next;
И не исправлено :) Мне кажется, Вы говорили, что баллов за домашки как-то мало, а тут вот, выбрасываете их на ветер. Всего-то и надо было `if (current == current->next) { list-> head = NULL; list->tail = NULL; }`

2020-12-26 10:48 UTC, merged