new solution of 6.1 added
ValentinaShvetsova/Homework pull request #14
Opened 2020-11-03 16:58 UTC by ValentinaShvetsova

2020-11-15 13:17 UTC, yurii-litvinov requested changes
По существу всё ок, но надо тесты ещё

2020-11-15 13:17 UTC, yurii-litvinov commented on Homework6/SortedList/List.c
> +	{
Опять со скобками что-то не так :)

2020-11-15 13:17 UTC, yurii-litvinov commented on Homework6/SortedList/List.c
> +	while (current != NULL && current->value != value) {
Ну на самом деле мы знаем, что список сортированный, так что если значения уже больше искомого, то можно дальше не искать

2020-11-15 13:17 UTC, yurii-litvinov commented on Homework6/SortedList/List.h
> +struct List* createList();
И тоже нужен комментарий. На самом деле, и к структуре List бы комментарий неплохо, типа что она представляет

2020-11-15 13:17 UTC, yurii-litvinov commented on Homework6/SortedList/Source.c
> +		printf("Choose the command:\n 0)Exit\n 1)Add value in list\n 2)Delete value from list\n 3)Print list\n");
Лучше разбить на несколько printf-ов (по одному на строку), чтобы оно в коде выглядело примерно так же, как на консоли. И тогда вынести в отдельную функцию.

2020-11-23 17:49 UTC, yurii-litvinov requested changes
Надо ещё немного поправить

2020-11-23 17:49 UTC, yurii-litvinov commented on Homework6/SortedList/List.c
> +	struct Node* newNode = malloc(sizeof(struct Node));
Кстати, интересно, а Вы умеете объяснять, почему иногда используете calloc, а иногда malloc?

2020-11-23 17:49 UTC, yurii-litvinov commented on Homework6/SortedList/List.c
> +	return newList;
Ну и, кстати, умеете объяснять, зачем здесь временная переменная newList и можно ли без неё?

2020-11-23 17:49 UTC, yurii-litvinov commented on Homework6/SortedList/List.c
> +		newNode->next = temp;
```c
newNode->next = list->head;
list->head = newNode;
```
В полтора раза короче :) Хотя, может, и менее читаемо.

2020-11-23 17:49 UTC, yurii-litvinov commented on Homework6/SortedList/List.c
> +	if (current->value != value) {
Так ведь current тут уже может быть NULL, упадёт

2020-11-23 17:49 UTC, yurii-litvinov commented on Homework6/SortedList/List.h
> +// This structure consist pointers to next and previous element, its own element
Не совсем. Вы пишете, из чего она состоит, а надо писать, что она из себя представляет. Это всё равно, что знакомиться с человеком в духе "Привет, я Валентина, у меня есть лёгкие и печень" :) В данном случае "This structure represents sorted list --- a container that allows to add and remove values and keeps values sorted"

2020-11-23 17:49 UTC, yurii-litvinov commented on Homework6/SortedList/Source.c
> +	printf(" 3)Print list:\n");
А почему тут пробел в начале?

2020-11-23 17:49 UTC, yurii-litvinov commented on Homework6/SortedList/Source.c
> +void commandVariation() {
Функции должны называться глаголами в повелительной форме. printCommands, например.

2020-11-23 17:49 UTC, yurii-litvinov commented on Homework6/SortedList/Source.c
> +		return false;
Так в случае провала теста уже выделенная память утечёт

2020-11-23 17:49 UTC, yurii-litvinov commented on Homework6/SortedList/Source.c
> +}
И опять-таки, тестовое покрытие минимально, я могу победить такие тесты, просто запоминая, вызывали addValue/deleteValue или нет.

2020-12-01 17:56 UTC, ValentinaShvetsova commented on Homework6/SortedList/List.c
> +	struct Node* newNode = malloc(sizeof(struct Node));
malloc используется обычно для выделения памяти под одиночные элементы, а calloc - под массивы.
Вообще, вы говорили лучше использовать calloc, но я иногда забываю

2020-12-01 17:57 UTC, ValentinaShvetsova commented on Homework6/SortedList/List.c
> +	return newList;
Ну, мы должны вернуть структуру список, я её создаю и возвращаю.

2020-12-01 18:12 UTC, ValentinaShvetsova commented on Homework6/SortedList/Source.c
> +}
Да, согласна

2020-12-08 11:57 UTC, yurii-litvinov commented on Homework6/SortedList/List.c
> +	return newList;
Не-а. Мы должны вернуть указатель на память, выделенную под структуру список, `calloc(1, sizeof(struct List));` как раз это и делает, так что можно `return calloc(1, sizeof(struct List));`. У Вас же тут выделяется память, указатель возвращается calloc-ом и запоминается во временную переменную newList, после чего читается из newList и возвращается.

2020-12-08 12:00 UTC, yurii-litvinov commented on Homework6/SortedList/List.c
> +	struct Node* newNode = malloc(sizeof(struct Node));
Не-а :) calloc действительно удобнее использовать для массивов, потому что он, в отличие от malloc, принимает количество элементов, но его основная фишка в том, что он инициализирует память нулями, в отличие от malloc, который её не трогает. Так что когда Вам и так надо заполнить память ненулевыми значениями, логичнее будет выделить её malloc-ом и заполнить, а если нужно нулевыми или ещё непонятно, чем, то calloc-ом.

2020-12-08 12:08 UTC, yurii-litvinov approved these changes
Окей, зачтена

2020-12-08 12:08 UTC, yurii-litvinov commented on Homework6/SortedList/Source.c
> +		return false;
А тут не поправили

2020-12-08 12:08 UTC, yurii-litvinov commented on Homework6/SortedList/Source.c
> +	deleteValue(list, 10);
Кстати, странно, addValue сначала принимает значение, потом список, deleteValue сначала список, потом значение. Запутаете пользователя

2020-12-08 12:08 UTC, yurii-litvinov commented on Homework6/SortedList/Source.c
> +}
Быть согласной недостаточно :) Что ж Вы так не любите тесты писать?..

2020-12-08 13:36 UTC, merged