Hw7.1
ValentinaShvetsova/Homework pull request #16
Opened 2020-11-11 16:45 UTC by ValentinaShvetsova

2020-11-22 18:13 UTC, yurii-litvinov requested changes

2020-11-22 18:13 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.h
> +//This function create Tree
`// This function create**s** Tree`, а то как-то не по-английски. И пробел после // бы не помешал

2020-11-22 18:13 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.h
> +void insert(int key, char* value, struct Node* node);
А про Node никто не знает тут. И не уверен, что должен знать, потому что это же абстракция словаря, которая может быть реализована и без всяких Node. Возможно, этой и всем функциям, которые упоминают Node, просто не место в .h-нике.

2020-11-22 18:13 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Source.c
> +		return false;
Так мы потеряем всю память, выделенную под дерево

2020-11-22 18:13 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Source.c
> +	char* result = calloc(1, sizeof(char*));
Не пригодилось, да ещё и память утекла. В условии специально сказано следить за памятью :)

2020-11-22 18:13 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Source.c
> +}
Надо (всегда) пустую строчку между функциями

2020-11-22 18:13 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Source.c
> +	if (!tests) {
А тесты на самом деле не вызываются, "()" забыли

2020-11-22 18:13 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Source.c
> +		printf("3)Check whether the key is in the dictionary or not\n4)Delete key and value\n");
Лучше по printf-у на каждый кусок строки до \n, чтобы в коде оно выглядело примерно так же, как в консоли. И вынести печать меню в отдельную функцию тогда, чтобы место тут не занимало

2020-11-22 18:13 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Source.c
> +				printf("Value for this key wasn't find\n");
wasn't f**ou**nd. Вас вряд ли числанут за прогу (хотя всякое бывает), а вот за английский могут вполне

2020-11-22 18:13 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +		node->value = value;
А так мы старое значение не удалим, утечка памяти

2020-11-22 18:13 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +			newNode->parent = node;
Возможно, стоило в отдельную функцию это вынести

2020-11-22 18:13 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +	char* newValue = calloc(101, (sizeof(char*)));
101 стоило бы задефайнить в .h-нике и использовать и в main тоже, чтобы у дерева и остальной программы были одинаковые представления о максимальной длине строки

2020-11-22 18:13 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Source.c
> +	}
Не убедительно. Рассматривается только удаление листовой вершины, это один из четырёх случаев, причём буквально самый простой. Надо больше тестов.

2020-11-22 18:13 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +	}else if (node->key > key) {
Пробела не хватает

2020-11-22 18:13 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +	}
Это тот же по сути спуск по дереву, что и в get, можно унифицирвоать. И даже со вставкой-удалением можно унифицировать, потому что там тоже поиск в дереве нужен, но это требует несколько больших усилий.

2020-11-22 18:13 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +			node->value = helpingNode->value;
Тоже утечка памяти

2020-11-22 18:13 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +		}
А ещё неплохо бы во всех случаях удалить node и всё, что в нём есть

2020-11-22 18:13 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +			free(node->key);
key же int, а не указатель. Это креш :)

2020-11-22 18:13 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +			free(node->parent);
Сам node не удалили, зато убили родителя. Хитрый план :)

2020-11-22 18:13 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +}
Это можно унифицировать с deleteNode, если там проверять, что у узла есть parent при необходимости к нему обратиться (правда, придётся передавать и tree, либо node по указателю, чтобы root обновить). В любом случае, переиспользовать куски кода явно можно.

2020-11-22 18:13 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +	{
Скобки внезапно в K&R-стиле, выше по-другому

2020-11-22 18:13 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +	free(node->key);
Оно правда работает? :)

2020-12-01 18:36 UTC, ValentinaShvetsova commented on Homework7/Dictionary/ATDDictionary/Tree.h
> +//This function create Tree
Когда-нибудь я выучу грамматику

2020-12-01 18:56 UTC, ValentinaShvetsova commented on Homework7/Dictionary/ATDDictionary/Source.c
> +				printf("Value for this key wasn't find\n");
Я в лучшей траектории, обижаете(
Просто мозг не может одновременно думать над программированием и английским пока.

2020-12-01 19:01 UTC, ValentinaShvetsova commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +			newNode->parent = node;
Оно вроде бы используется в таком виде только дважды, поэтому выигрыша не будет

2020-12-01 19:17 UTC, ValentinaShvetsova commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +	free(node->key);
free(node.key)? - Да, я и не думала, что так нельзя

2020-12-01 20:25 UTC, ValentinaShvetsova commented on Homework7/Dictionary/ATDDictionary/Source.c
> +	}
Хорошо, я подумаю над новыми тестами

2020-12-19 16:35 UTC, yurii-litvinov requested changes

2020-12-19 16:35 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Source.c
> +}
Пустой строчки не хватает

2020-12-19 16:35 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Source.c
> +	}
И как? :)

2020-12-19 16:35 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +		node->value = value;
Да нет же! `free(node->value);` :)

2020-12-19 16:35 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +		free(node->key);
Да это вообще упадёт, key же не указатель

2020-12-19 16:35 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +			newNode->parent = node;
Трижды, а если что-то используется трижды, то уже надо задуматься. Но это не критично, можно не править.

2020-12-19 16:35 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +	}
Напоминаю. И это, кажется, то же самое, что contains

2020-12-19 16:35 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +	return false;
Это в одну строчку надо записать, без всяких if-ов. Результат сравнения и так булевый тип, тут написано, что если true, вернуть true, а если false, вернуть false

2020-12-19 16:35 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +			free(node->key);
Не-а

2020-12-19 16:35 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +
После "{" пустые строки обычно не ставят

2020-12-19 16:35 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +				newRoot = tree->root->leftChild;
Тут написано "А давайте положим в newRoot NULL, ой нет, я передумала" :)

2020-12-19 16:35 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +				free(tree->root->key);
Нет :)

2020-12-19 16:35 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +				free(tree->root->key);
Нет :)

2020-12-19 16:35 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +		tree->root->value = helpNode->value;
А так тоже память утечёт. Сделайте мноооого тестов и проверьте отладчиком памяти, что всё ок

2020-12-19 16:35 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +	free(tree->root->key);
Нет :)

2020-12-19 16:35 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +	free(node->key);
Так и нельзя. node->key не указатель, это просто число. При попытке сделать free содержимое node->key кастается к void*, то есть интерпретируется как адрес памяти, который free пытается удалить, но операционная система не даёт это сделать, потому что такого адреса никогда и не выделяла.

2020-12-27 13:22 UTC, yurii-litvinov requested changes

2020-12-27 13:22 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +{
И тут скобка не как везде

2020-12-27 13:22 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +#define SIZE 101
Та же проблема с выделением памяти, которую я уже комментил в какой-то из предыдущих домашек.

2020-12-27 13:22 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +			return;
Так, а какова дальнейшая судьба newNode? Уж не мемлик ли это? Но, честтно говоря, смысл его существования непонятен, он просто некоторое непродолжительное время хранит value и key, и с этим могли бы справиться две обычные переменные.

2020-12-27 13:22 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.h
> +#define SIZE 101
Оно зря и тут и в .c-шнике объявлено, в одном месте поменяем, в другом забудем, и всё

2020-12-27 16:14 UTC, ValentinaShvetsova commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +#define SIZE 101
Лишние инклюды?

2020-12-28 19:24 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +#define SIZE 101
Нет-нет, выделение памяти. Типа надо не SIZE выделять, а strlen(...) + 1

2020-12-28 19:37 UTC, yurii-litvinov approved these changes
Хорошо, зачтена --- ещё есть что поправить, но ладно

2020-12-28 19:37 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +			return;
Это уже не мемлик, но смысл его существования всё ещё непонятен (это антипаттерн "Полтергейст" --- временный объект, который не делает ничего полезного)

2020-12-28 19:37 UTC, yurii-litvinov commented on Homework7/Dictionary/ATDDictionary/Tree.c
> +				newRoot = tree->root->rightChild;
Нееет. `struct Node* newRoot = tree->root->rightChild;`

2020-12-28 19:48 UTC, merged