7.2
ValentinaShvetsova/Homework pull request #17
Opened 2020-11-13 17:53 UTC by ValentinaShvetsova

2020-11-23 14:06 UTC, yurii-litvinov requested changes
Очень круто. Почти зачтена.

2020-11-23 14:06 UTC, yurii-litvinov commented on Homework7/7.2/ParseTree/Tree.h
> +struct Tree* buildTree(char* string);
Мм, with data from file или из строки? Если из файла и парамер string --- имя файла, то его стоило бы переименовать, если из строки, то комментарий не правдив.

2020-11-23 14:06 UTC, yurii-litvinov commented on Homework7/7.2/ParseTree/Tree.h
> +//This function delete tree
delete**s**, и нужно пробел после //, тут и выше

2020-11-23 14:06 UTC, yurii-litvinov commented on Homework7/7.2/ParseTree/Source.c
> +	if (!tests) {
Тесты не запускаются, () забыли

2020-11-23 14:06 UTC, yurii-litvinov commented on Homework7/7.2/ParseTree/Tree.c
> +	return newTree;
На самом деле, можно было сразу `return calloc(1, sizeof(struct Tree));`

2020-11-23 14:06 UTC, yurii-litvinov commented on Homework7/7.2/ParseTree/Tree.c
> +int numberBuilding(char *string, int **position) {
position принимается как `int**`, но используется всегда только как `**position`. Может, стоило её принимать как `int*`

2020-11-23 14:06 UTC, yurii-litvinov commented on Homework7/7.2/ParseTree/Tree.c
> +	if (string[*position] == '+' || string[*position] == '-' || string[*position] == '*' || string[*position] == '/') {
А есть же isOperation

2020-11-23 14:06 UTC, yurii-litvinov commented on Homework7/7.2/ParseTree/Tree.c
> +{
А тут скобка одна на строке, а во всех остальных местах на предыдущей строчке

2020-11-23 14:06 UTC, yurii-litvinov commented on Homework7/7.2/ParseTree/Tree.c
> +{
И тут скобка неконсистентна

2020-12-02 17:13 UTC, ValentinaShvetsova commented on Homework7/7.2/ParseTree/Tree.c
> +	if (string[*position] == '+' || string[*position] == '-' || string[*position] == '*' || string[*position] == '/') {
isOperation работает для узлов дерева

2020-12-19 19:08 UTC, yurii-litvinov approved these changes
Окей, зачтена

2020-12-19 19:08 UTC, yurii-litvinov commented on Homework7/7.2/ParseTree/Tree.c
> +	if (string[*position] == '+' || string[*position] == '-' || string[*position] == '*' || string[*position] == '/') {
Ну да, а если сделать функцию, которая бы принимала символ и делала вот это сравнение, и использовать её и в isOperation, и тут, было бы лучше. Копипаст суть ересь.

2020-12-22 14:49 UTC, merged