Hw8
ValentinaShvetsova/Homework pull request #18
Opened 2020-11-17 16:20 UTC by ValentinaShvetsova

2020-12-07 11:16 UTC, yurii-litvinov requested changes
Ещё нужны тесты.

И обратите внимание, я только в одном месте про каждую ошибку написал, но некоторые встречаются ещё много где --- надо разобраться, что не так, и применить полученные от этого знания во всех остальных подходящих частях программы.

2020-12-07 11:16 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.h
> +struct Node;
Это не стоит выносить в заголовочный файл, это деталь реализации дерева. Да и вообще стоило бы сделать тип данных "Словарь", а не "Дерево", но это уж дело вкуса

2020-12-07 11:16 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.h
> +//This funtion deletes Tree
fun**с**tion, опечатка

2020-12-07 11:16 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.h
> +void addValue(struct Tree* tree, int key, char* value);
По условию просили и ключи тоже типа char * :)

2020-12-07 11:16 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +	}
Это можно было записать тернарным оператором, было бы короче и симпатичнее: `node->height = (leftHeight > rightHeight ? leftHeight : rightHeight) + 1;`

2020-12-07 11:16 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +	baseOfRotation = root->rightChild;
Тут выделяется память под Node, указатель на неё присваивается в baseOfRotation, затем тут же забывается и в baseOfRotation записывается root->rightChild. Утечка памяти. Просил же поправить :)

2020-12-07 11:16 UTC, yurii-litvinov commented on Homework8/AVLTree/Source.c
> +				printf("Value for this key wasn't find\n");
"wasn't f**ou**nd" всё-таки

2020-12-07 11:16 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +	struct Tree* newTree = calloc(1, sizeof(struct Tree*));
Всё-таки `sizeof(struct Tree)` --- Вы выделяете память под Tree, не под указатель на Tree. Работает всё потому, что благодаря стечению обстоятельств Tree равна по размеру Tree * (просто потому, что Tree содержит как раз только один указатель).

2020-12-07 11:16 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +			newNode->parent = node;
Что-то копипаст. Стоило вынести в отдельную функцию.

2020-12-07 11:16 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +	strcpy(newValue, value);
Ерунда же написана :) Вы выделяете память под один char*, возвращаете на него указатель (типа char **, это ж указатель на char *), и копируете в то место, куда он указывает, строку из value (но под её хранение никто памяти не выделял). Это же креш при первой же попытке free этой области.

2020-12-07 11:16 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +		free(node->height);
Не-а. free принимает только указатели и освобождает участок памяти, **на который указывает указатель**. node->key int, он ни на что не указывает, и память, выделенная под него, освободится во время free(node) (потому что он часть node, он лежит внутри, а не отдельно). Вот free(node->value) делать надо, потому что node->value --- char *, указатель на строку, которая лежит отдельно от node (и node->value просто на неё ссылается). Правило очень просто --- если пишете malloc/calloc, должен быть и free, если не пишете, то не должен быть. Вы ж не делаете нигде node->key = malloc(...).

2020-12-20 18:06 UTC, yurii-litvinov requested changes

2020-12-20 18:06 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +	}
Поправьте всё-таки это, пожалуйста

2020-12-20 18:06 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.h
> +bool contain(struct Tree* tree, char* key);
"contains". "Contain" --- это скорее "сдержать, изолировать"

2020-12-20 18:06 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +		node->value = value;
Так указатель на старое значение потеряется, утечка памяти. В node->value же лежала какая-то строка до этого.

2020-12-20 18:06 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +			newNode->parent = node;
Окей. Это копипаст и надо вынести создание узла в отдельную функцию.

2020-12-20 18:06 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +			newNode->value = value;
Это значит, что дерево принимает на себя управление памятью под key и value, то есть вызывающий не имеет права больше их хранить и не должен их ни удалять, ни переиспользовать. Это вполне допустимо, но у Вас не так.

2020-12-20 18:06 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +	strcpy(newValue, value);
Типа мы это обсудили, но Вы решили не править? :)

2020-12-20 18:06 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +}
get и find суть одно и то же

2020-12-20 18:06 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +		return value;
А точно надо возвращать копию value? А вызывающий знает, что это копия и ему надо память удалить?

2020-12-20 18:06 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +	mostRightOnTheLeft = node->leftChild;
Тут написано "давайте выделим память под хранение Node и запишем указатель на неё в mostRightOnTheLeft. А хотя ну его к чёрту, лучше положим туда node->leftChild, а уже выделенная память пусть так и висит в куче, всеми забытая"

2020-12-20 18:06 UTC, yurii-litvinov commented on Homework8/AVLTree/Source.c
> +}
И пустой строки между функциями не хватает

2020-12-27 12:19 UTC, yurii-litvinov requested changes
Уже почти. Остались вполне разумные ошибки, которые Вы уже точно можете поправить.

2020-12-27 12:19 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +	char* newKey = calloc(SIZE, sizeof(char));
Тут правильнее strlen(key) + 1 вместо SIZE. Потому что если SIZE больше, чем длина key, это расход памяти впустую, если меньше, то падение программы

2020-12-27 12:19 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +	}
Тоже можно было в одну строчку, `return node == NULL ? 0 : node->height;`

2020-12-27 12:19 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +		root->parent = NULL;
createNode это и так делает

2020-12-27 12:19 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +}
Ну ладно, минус балл и забудем об этом :)

2020-12-27 12:19 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +	to->key = newKey;
А если в to что-то уже было, то утечка памяти

2020-12-27 12:19 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +				node->parent->leftChild = node->rightChild;
Мм, а return тут не делается и мы потом в 279 строчке занулим указатель на сына, потеряв полдерева?

2020-12-27 12:19 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.h
> +// This function ctreates tree
"ctreates", опечатка

2020-12-27 12:19 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.h
> +// This function add value in the tree
adds

2020-12-27 12:19 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.h
> +//This function check whether tree contains value by key
"checks", и пробел после // надо :)

2020-12-27 12:19 UTC, yurii-litvinov commented on Homework8/AVLTree/Source.c
> +	char key1[] = "11";
Лучше const char *key1 = "11";. Потому что по объявлению char key1[]  можно подумать, что key1 можно менять, что неправда и закончится крешем, потому что строковые литералы неизменяемы.

2020-12-27 12:19 UTC, yurii-litvinov commented on Homework8/AVLTree/Source.c
> +		return false;
Так вся память, выделенная под дерево, утечёт

2020-12-27 17:05 UTC, ValentinaShvetsova commented on Homework8/AVLTree/AVLTree.c
> +}
Не-не, я поправила. Мне и так баллов не хватает(

2020-12-27 19:59 UTC, yurii-litvinov requested changes
Если АВЛ-дерево ещё не снится Вам в кошмарах, то скоро будет

2020-12-27 19:59 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +#define SIZE 100
Удалить SIZE, чтобы гарантировать, что нигде не осталась старая плохая система выделения памяти, было бы хорошей идеей

2020-12-27 19:59 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +	char* newValue = calloc(SIZE, sizeof(char));
Ну, для value применимы те же рассуждения, что и для key

2020-12-27 19:59 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +	char* newValue = calloc(SIZE, sizeof(char));
И тут. В общем, надо убрать SIZE и поправить все места, где компилятор ругается

2020-12-27 19:59 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +		return;
Так newKey и newValue утекут

2020-12-27 19:59 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +		return;
Так newValue утечёт

2020-12-27 19:59 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +	insert(tree->root, newKey, newValue);
А вообще, insert же выделит под хранение key и value память, зачем newKey и newValue вообще? Проверяли на утечки памяти?

2020-12-27 19:59 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +}
Да где же? Я имел в виду, что можно сделать getNode, который бы по ключу возвращал узел, а getKey и getValue бы его использовали и писались в одну строчку

2020-12-27 19:59 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +		return;
newValue утечёт

2020-12-27 19:59 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +			free(node);
Надо сделать что-то вроде freeNode и запихать туда эти три строчки, потому что они только в этой функции четыре раза встречаются, а ещё есть deleteRoot и deleteChildren...

2020-12-27 19:59 UTC, yurii-litvinov commented on Homework8/AVLTree/Source.c
> +	char *value3 = "left";
Таки const char *, и надо, чтобы работало просто addValue(tree, "11", "right");, без всяких временных переменных

2020-12-28 15:35 UTC, yurii-litvinov requested changes
Уже совсем почти

2020-12-28 15:35 UTC, yurii-litvinov commented on Homework8/AVLTree/Source.c
> +	if (strcmp(getValue(tree, key2), value2) != 0) {
Так можно было и дальше, вместо key2 просто писать "12"

2020-12-28 15:35 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +	struct Node* newNode = calloc(1, sizeof(struct Node));
Теоретически, каждая аллокация может провалиться, и надо уметь на это реагировать

2020-12-28 15:35 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +	}
У Вас же есть функция getHeight, которая делает как раз это

2020-12-28 15:35 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +	return node->value;
Ежели таковой Node найдётся... А если нет, то упадёт

2020-12-28 15:35 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +}
А find же тоже выражается через getNode

2020-12-28 18:53 UTC, yurii-litvinov requested changes
Почти-почти-почти зачтена.

2020-12-28 18:53 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +		return NULL;
А так теряется уже выделенная память под newNode :)

2020-12-28 18:53 UTC, yurii-litvinov commented on Homework8/AVLTree/AVLTree.c
> +	}
"Как раз это" включает в себя проверку на NULL, то есть можно было вообще `int leftHeight = getHeight(node->leftChild);`, без всяких if-ов

2020-12-28 18:53 UTC, yurii-litvinov commented on Homework8/AVLTree/Source.c
> +	if (contains(tree, "13")) {
И тогда все объявленные выше строковые константы становятся не нужны и их можно смело удалить

2020-12-28 19:39 UTC, yurii-litvinov approved these changes
👍

2020-12-28 19:47 UTC, merged