Hw9.1
ValentinaShvetsova/Homework pull request #20
Opened 2020-11-25 18:47 UTC by ValentinaShvetsova

2020-12-07 16:09 UTC, yurii-litvinov requested changes
А ещё нужны тесты. Так-то в целом нормально, только баг  с выделением памяти всё портит.

2020-12-07 16:09 UTC, yurii-litvinov commented on Homework9/9.1/HashTable/List.c
> +		strcpy(newValue, value);
Не-а, calloc(1, sizeof(char*)); маловато, надо strlen(value) + 1 char-ов выделять. Так падает сразу.

2020-12-07 16:09 UTC, yurii-litvinov commented on Homework9/9.1/HashTable/List.c
> +		return true;
Некий копипаст, стоило бы вынести в отдельную функцию

2020-12-07 16:09 UTC, yurii-litvinov commented on Homework9/9.1/HashTable/List.c
> +
Лишняя пустая строчка :) Больше одной подряд не принято

2020-12-07 16:09 UTC, yurii-litvinov commented on Homework9/9.1/HashTable/HashTable.vcxproj.filters
> +      <Filter>Файлы ресурсов</Filter>
Что-то пошло не так

2020-12-07 16:09 UTC, yurii-litvinov commented on Homework9/9.1/HashTable/Source.c
> +	deleteTable(table);
deleteTable в .h-нике не прописана, компилятор ругается

2020-12-07 16:09 UTC, yurii-litvinov commented on Homework9/9.1/HashTable/HashTable.vcxproj.filters
> +    <Text Include="input.txt">
Его тоже следовало бы выложить

2020-12-08 18:33 UTC, ValentinaShvetsova commented on Homework9/9.1/HashTable/HashTable.vcxproj.filters
> +      <Filter>Файлы ресурсов</Filter>
Почему?

2020-12-24 18:19 UTC, yurii-litvinov requested changes
Почти

2020-12-24 18:19 UTC, yurii-litvinov commented on Homework9/9.1/HashTable/List.c
> +	newList->head = NULL;
Он и так NULL, calloc это гарантирует

2020-12-24 18:19 UTC, yurii-litvinov commented on Homework9/9.1/HashTable/List.c
> +	char* newValue = calloc(strlen(value) + 1, sizeof(char*));
Может, Вам со временной переменной проще, и я не против, но вообще можно было сразу после создания newNode сделать `newNode->word = calloc(strlen(value) + 1, sizeof(char*));` и потом уже туда strcpy

2020-12-24 18:19 UTC, yurii-litvinov commented on Homework9/9.1/HashTable/List.c
> +		free(current);
Эта строка ровным счётом ничего не делает, current же NULL. free(NULL) просто return делает сразу. Но и хорошо, потому что current же курсор в существующем списке, и его free убило бы кого-то внутри списка, если бы всё пошло по плану :)

2020-12-24 18:19 UTC, yurii-litvinov commented on Homework9/9.1/HashTable/List.c
> +
Лишняя пустая строчка

2020-12-24 18:19 UTC, yurii-litvinov commented on Homework9/9.1/HashTable/Source.c
> +		return false;
Таблицу ведь надо удалить, тут и ниже. Ну и потом, разве это всё, что можно про неё проверить?

2020-12-24 18:19 UTC, yurii-litvinov commented on Homework9/9.1/HashTable/HashTable.vcxproj.filters
> +      <Filter>Файлы ресурсов</Filter>
Потому что это .c-файл, он должен быть в "Исходные файлы". Файлы ресурсов --- это файлы с данными. Кстати, спрашивайте в телеге лучше, тут я могу не заметить :)

2020-12-27 18:09 UTC, yurii-litvinov approved these changes
Ага, теперь всё ок, зачтена

2020-12-27 18:21 UTC, merged