Hw10
ValentinaShvetsova/Homework pull request #21
Opened 2020-11-30 18:17 UTC by ValentinaShvetsova

2020-12-08 07:49 UTC, yurii-litvinov requested changes
Алгоритмически и идейно всё правильно, но исполнение страдает (in fact, оно у меня даже не компилируется)

2020-12-08 07:49 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/List.c
> +	newList->head = NULL;
А он и так будет NULL, calloc всё инициализирует нулями. Так что можно даже в одну строчку, `return calloc(1, sizeof(struct List));`

2020-12-08 07:49 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/List.c
> +	list->tail->next = NULL;
Он ведь и так должен быть NULL, а эта строка упадёт, если список пустой

2020-12-08 07:49 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/List.h
> +#include <stdio.h>
Эти два инклюда вроде в заголовочном файле не используются, значит, не нужны

2020-12-08 07:49 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/Source.c
> +	}
Чтение из файла и заполнение графа надо в отдельную функцию вынести. Во-первых потому, что в main делается то же самое, так что копипаст, во-вторых и в главных --- это тоже тестировать надо.

2020-12-08 07:49 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/Source.c
> +	fclose(file);
Со столицами то же (можно всё и в одной функции делать)

2020-12-08 07:49 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/Source.c
> +	distributeCities(graph, size, capitals, numberOfCapitals, towns);
Компилятор не огорчает необъявленная функция?

2020-12-08 07:49 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/Source.c
> +	free(graph);
Удаление графа тоже явно претендент на отдельную функцию

2020-12-08 07:49 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/Source.c
> +	free(capitals);
Снова free(capitals)? Не падает от двойного удаления?

2020-12-08 07:49 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/Source.c
> +	struct List* answer2 = createList();
Кажется, их никто не удаляет

2020-12-08 07:49 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/Source.c
> +	int *pnumberOfLeftoverCities = malloc(sizeof(int));
Что за pnumber? :) И зачем выделять на куче память под один int, чем тут не устроило размещение на стеке вызовов?

2020-12-08 07:49 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/Source.c
> +			distance[i] = distance[currentVertex] + graph[currentVertex][i];
Тут несколько больше Дейкстры, чем было нужно --- по условию захватывался ближайший к государству город, не ближайший к столице, так что можно было "локальные" длины считать. Но так тоже хорошо, можно не переделывать (просто чуть сложнее получилось)

2020-12-08 07:49 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/RoadsAndTowns.vcxproj.filters
> +      <Filter>Файлы ресурсов</Filter>
Нет :)

2020-12-08 07:49 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/Source.c
> +	int** graph = (int*)malloc(size * size * sizeof(int));
Компилятор просил передать, что ему не нравится присвоение значения int* в переменную типа int** и что Вы его вывод не читаете :)

2020-12-09 16:10 UTC, ValentinaShvetsova commented on Homework10/RoadsAndTowns/Source.c
> +	int *pnumberOfLeftoverCities = malloc(sizeof(int));
Это указатель, как pointer, он у меня по идее должен изменяться в нескольких функциях, поэтому он указатель

2020-12-09 16:52 UTC, ValentinaShvetsova commented on Homework10/RoadsAndTowns/RoadsAndTowns.vcxproj.filters
> +      <Filter>Файлы ресурсов</Filter>
Это странно, у меня в проекте он в файлах ресурсов лежит.

2020-12-20 12:33 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/Source.c
> +	int *pnumberOfLeftoverCities = malloc(sizeof(int));
Это называется "венгерская нотация", когда тип переменной является частью её названия. Была популярна в коде Microsoft в 90-е (она и называется венгерской, потому что её венгерский по национальности сотрудник Microsoft насаждал). Вышла из моды ещё до Вашего рождения и с тех пор считается плохим стилем (по крайней мере, в языках со статической типизацией, типа С).

2020-12-20 12:34 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/RoadsAndTowns.vcxproj.filters
> +      <Filter>Файлы ресурсов</Filter>
Но должен-то в "Исходные файлы"

2020-12-20 13:16 UTC, yurii-litvinov requested changes
Куча предупреждений компилятора.

2020-12-20 13:16 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/List.c
> +	newNode->value = value;
newNode->next остаётся неинициализированным, кажется, и это портит всю структуру списка, потому что делает неверным `list->tail->next == NULL`, на что закладываются почти все остальные функции

2020-12-20 13:16 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/List.c
> +	}
Ещё у Вас есть tail, так что при удалении надо проверить, не является ли удаляемый элемент tail-ом

2020-12-20 13:16 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/List.c
> +}
И надо удалить сам список, и занулить указатель на него (так что принимать следует `struct List** list`)

2020-12-20 13:16 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/List.h
> +void deleteGraph(int** graph, int size);
Этой функции совершенно не надо быть в модуле со списком. Ни один нормальный человек тут и не подумает её искать, что может создать проблемы при сопровождении программы.

2020-12-20 13:16 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/List.c
> +	list->tail->next = NULL;
Он ведь и так должен быть NULL, это инвариант списка.

2020-12-20 13:16 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/List.c
> +}
И занулить указатель бы ещё, так что лучше принимать int*** :)

2020-12-20 13:16 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/List.c
> +	for (int i = 1; i < positionNumber; ++i) {
Если список пуст или просто такой позиции нет, всё упадёт

2020-12-20 13:16 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/Source.c
> +}
Пустой строки между функциями не хватает

2020-12-20 13:16 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/Source.c
> +	int **distance = (int*)malloc(size * size * sizeof(int));
Вы уверены, что тут size * size элементов должно быть?

2020-12-20 13:16 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/Source.c
> +	int *pnumberOfLeftoverCities = malloc(sizeof(int));
Выделять одно число на куче, чтобы в этой же функции его удалить --- это расписываться в непонимании работы с памятью

2020-12-20 13:16 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/Source.c
> +	}
Напоминаю

2020-12-24 17:06 UTC, ValentinaShvetsova commented on Homework10/RoadsAndTowns/List.c
> +	}
Зачем? List.tail.next у меня NULL, ничего плохого произойти не должно вроде бы

2020-12-24 18:10 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/List.c
> +	}
Так List.tail.next NULL, но когда Вы удаляете последний элемент, tail продолжает на него указывать, хотя на самом деле последним становится предпоследний элемент. И следующая попытка разыменования tail --- доступ к удалённой памяти

2020-12-24 18:31 UTC, ValentinaShvetsova commented on Homework10/RoadsAndTowns/Source.c
> +	int *pnumberOfLeftoverCities = malloc(sizeof(int));
Но ведь мне просто нужна переменная, которая будет меняться вне функции, почему так нельзя и как сделать по-другому?

2020-12-27 14:10 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/Source.c
> +	int *pnumberOfLeftoverCities = malloc(sizeof(int));
Так она разве меняется вне функции? Мы ж только вызываем другие функции, из этой функции не выходим всё время жизни этой переменной. Так что кадр стека и всё, что в нём лежит, доступно, то есть просто int numberOfLeftoverCities = 0; и потом передавать его как &numberOfLeftoverCities везде, где оно нужно

2020-12-27 14:22 UTC, yurii-litvinov requested changes

2020-12-27 14:22 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/Graph.h
> +void fillGraph(char* fileName);
А реализации нету

2020-12-27 14:22 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/Graph.c
> +#include "List.h"
А точно ли все эти хедеры нужны?

2020-12-27 14:22 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/List.c
> +	if (current->value != value) {
А если current равен NULL тут, что будет? Ведь если значение в списке не найдётся, именно NULL он и будет равен

2020-12-27 14:22 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/List.c
> +		if (current == NULL) {
Нееет, current точно не NULL, иначе мы бы упали ещё на current->value != value. Да и free бы тогда ничего не сделал

2020-12-27 14:22 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/List.c
> +		struct Node* temp = (list)->head->next;
А тут скобки-то не нужны

2020-12-27 14:22 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/List.c
> +	return current->value;
А теперь не упадёт, но радостно вернёт значение последнего элемента, что может быть то, что нужно, а может и нет

2020-12-27 14:22 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/List.c
> +		return NULL;
0. Мы же int возвращаем

2020-12-27 14:22 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/List.c
> +		}
А иначе?

2020-12-27 14:22 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/Source.c
> +
А тут вот лишняя пустая строчка :)

2020-12-27 14:22 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/Source.c
> +	int* pnumberOfLeftoverCities = malloc(sizeof(int));
Тут всё-таки поправьте

2020-12-27 14:22 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/Source.c
> +	}
Чтение графа надо таки отдельной функцией сделать

2020-12-27 17:21 UTC, ValentinaShvetsova commented on Homework10/RoadsAndTowns/Source.c
> +	}
Но вы ведь разрешили не делать.

2020-12-27 20:02 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/Source.c
> +	}
Зря :) Но окей.

2020-12-27 20:17 UTC, yurii-litvinov requested changes
Оно даже не компилится. Прекратите паниковать и старайтесь править аккуратно. Вас уже не отчислят за прогу после первого семестра. Это уже существенно лучше, чем у многих до Вас :)

2020-12-27 20:17 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/List.c
> +	}
А что с tail?

2020-12-27 20:17 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/List.c
> +		list->head = temp;
А deleteValue сам выставит list->head, так что 65 и 67 строчки, кажется, вообще не нужны

2020-12-27 20:17 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/List.h
> +void deleteGraph(int** graph, int size);
Напоминаю

2020-12-27 20:17 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/Source.c
> +	int numberOfLeftoverCities = *numberOfLeftoverCities;
Лол. Компилятор не возражает?

2020-12-27 20:17 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/Source.c
> +	int* numberOfLeftoverCities = malloc(sizeof(int));
malloc(sizeof(int)); надо убрать

2020-12-28 19:07 UTC, yurii-litvinov approved these changes
Хорошо, зачтена

2020-12-28 19:07 UTC, yurii-litvinov commented on Homework10/RoadsAndTowns/Source.c
> +	int** distance = (int*)malloc(size * sizeof(int));
`(int**)malloc(size * sizeof(int));`, компилятор же ругается, тут и ещё в паре мест. Вообще нельзя, чтобы компилятор ругался.

2020-12-28 19:49 UTC, merged