2sem1.2
ValentinaShvetsova/Homework pull request #34
Opened 2021-02-18 09:18 UTC by ValentinaShvetsova

new solution added

2021-02-18 14:42 UTC, ValentinaShvetsova commented
> new solution added

Не бейте сильно тапком, но обратный оптимизированный чего-то не работает.

2021-02-18 15:41 UTC, yurii-litvinov requested changes
Прямое преобразование, как я понимаю, то, что называется "наивным", с явным построением таблицы вращений, оно на балл "дешевле" "настоящего" BWT. Обратное действительно не работает :) Там temp неправильно заполняется вроде, не строит перестановку. Надо поотлаживаться (в крайнем случае, на бумажке написать, что должно быть, и пошагово пройтись, смотря на значения temp, line и alphabetOfString).

И ещё это может быть несколько преждевременно, но тесты нужны :)

2021-02-18 15:41 UTC, yurii-litvinov commented on Homework2/BubbleSort/BubbleSort/BubbleSort.vcxproj
> +      <SDLCheck Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">false</SDLCheck>
Тоже какие-то лишние коммиты в пуллреквесте :) Замерджили бы все C++ные изменения в мастер, да и всё

2021-02-18 15:41 UTC, yurii-litvinov commented on SecondSemester/Homework1/BWT/Program.cs
> +            char temp;
temp вне цикла не нужен, следовательно, и объявлять его надо на 13-й строчке, сразу `int temp = transpositionTable[i, t];`

2021-02-18 15:41 UTC, yurii-litvinov commented on SecondSemester/Homework1/BWT/Program.cs
> +        }
По стайлгайду надо пустые строки между методами всегда

2021-02-18 15:41 UTC, yurii-litvinov commented on SecondSemester/Homework1/BWT/Program.cs
> +            for(int t = 0; t < size; ++t)
Пробела после for не хватает

2021-02-18 15:41 UTC, yurii-litvinov commented on SecondSemester/Homework1/BWT/Program.cs
> +                if(transpositionTable[i, t].CompareTo(transpositionTable[j, t]) < 0)
И после if. Интересно, Visual Studio же обычно сама форматирует код правильно :)

И ниже надо поправить

2021-02-18 15:41 UTC, yurii-litvinov commented on SecondSemester/Homework1/BWT/Program.cs
> +                } else if (transpositionTable[i, t].CompareTo(transpositionTable[j, t]) > 0)
char-ы же можно обычным < или > сравнивать

2021-02-18 15:41 UTC, yurii-litvinov commented on SecondSemester/Homework1/BWT/Program.cs
> +        public static void Sort(char[,] transpositionTable, int size)
size не надо передавать, массивы в C# сами знают свой размер. Было где-то на слайдах :)

2021-02-18 15:41 UTC, yurii-litvinov commented on SecondSemester/Homework1/BWT/Program.cs
> +                transpositionTable[0,i] = line[i];
А тут пробела после запятой не хватает

2021-02-18 15:41 UTC, yurii-litvinov commented on SecondSemester/Homework1/BWT/Program.cs
> +        public static void SwapStrings(char[,] transpositionTable, int size, int i, int j)
На самом деле, все методы, которые извне не должны быть доступны, должны быть private (это типа функций в .c-файлах, тогда как public --- это типа функций в .h-никах)

2021-02-18 15:41 UTC, yurii-litvinov commented on SecondSemester/Homework1/BWT/Program.cs
> +            int alphabetSymbols = line.Distinct().Count();
Мне кажется, нигде не потребовалось

2021-02-18 15:41 UTC, yurii-litvinov commented on SecondSemester/Homework1/BWT/Program.cs
> +                sum = sum + countOfSymbols[i];
sum += countOfSymbols[i];

2021-02-18 15:41 UTC, yurii-litvinov commented on SecondSemester/Homework1/BWT/Program.cs
> +            char[] res2 = ReverseBWT(result, transpositionTable);
Этак Вы предлагаете помимо строки передавать ещё матрицу? Не, хочется, чтобы BWT возвращал строку и ReverseBWT только строку принимал. Иначе получится архиватор, который раздувает файл в N^2 раз, такой никому не нужен :)

2021-02-18 15:41 UTC, yurii-litvinov commented on SecondSemester/Homework1/BWT/Program.cs
> +            }
Можно было var resultString = new String(result); Console.WriteLine(resultString);. И не мучиться с массивами char-ов.

2021-02-18 17:26 UTC, ValentinaShvetsova commented on SecondSemester/Homework1/BWT/Program.cs
> +                } else if (transpositionTable[i, t].CompareTo(transpositionTable[j, t]) > 0)
А можно так оставить?

2021-03-01 12:34 UTC, yurii-litvinov requested changes
Теперь алгоритмически вроде всё ок, но качество кода ещё надо улучшать.

2021-03-01 12:34 UTC, yurii-litvinov commented on SecondSemester/Homework1/BWT/Program.cs
> +                } else if (transpositionTable[i, t].CompareTo(transpositionTable[j, t]) > 0)
![image](https://user-images.githubusercontent.com/706768/109496502-c9dd9f00-7aa1-11eb-95fd-034d83a68097.png)
Можно. Но зачем? :)

2021-03-01 12:34 UTC, yurii-litvinov commented on SecondSemester/Homework1/BWT/Program.cs
> +            var numberOfString = BWT(line, transpositionTable).Item2;
Теперь нет нужды тут transpositionTable  создавать, с этим прекрасно справится сам BWT. Всё, что можно не передавать в функцию, нельзя передавать в функцию.

2021-03-01 12:34 UTC, yurii-litvinov commented on SecondSemester/Homework1/BWT/Program.cs
> +            var resultString = new String(result);
То же касается возврата массива символов, а не строки. BWT нетрудно преобразовать Item1 в строку самостоятельно, зачем заставлять вызывающего это делать? Абстракция должна быть удобна для использования, а не заставлять выполнять пляски с бубном при каждом вызове.

2021-03-01 12:34 UTC, yurii-litvinov commented on SecondSemester/Homework1/BWT/Program.cs
> +            var numberOfString = BWT(line, transpositionTable).Item2;
Угадайте, как сделать этот код в два раза быстрее. Это можно сделать и только используя Ваши текущие знания, но в C# ещё и декомпозиция есть: var (result, numberOfString) = ...

2021-03-01 12:34 UTC, yurii-litvinov commented on SecondSemester/Homework1/BWT/Program.cs
> +            var resultString2 = new String(res2);
Тут тоже, может, имеет смысл возвращать сразу строку и сразу без стоп-символа

2021-03-01 12:34 UTC, yurii-litvinov commented on SecondSemester/Homework1/BWT/Program.cs
> +            return true;
За такое даже в первом семестре отчисляли :)

2021-03-01 12:34 UTC, yurii-litvinov commented on SecondSemester/Homework1/BWT/Program.cs
> +            if (result.CompareTo("annb$aa") != 0)
Проверять строки на равенство можно и `==`

2021-03-03 15:25 UTC, yurii-litvinov approved these changes
Ага, теперь всё ок

2021-03-03 15:25 UTC, yurii-litvinov commented on SecondSemester/Homework1/BWT/Program.cs
> +                } else if (transpositionTable[i, t] > (transpositionTable[j, t]))
Правильнее
```csharp
}
else if (transpositionTable[i, t] > (transpositionTable[j, t]))
{
```

2021-03-03 15:25 UTC, yurii-litvinov commented on SecondSemester/Homework1/BWT/Program.cs
> +            return (oldString1 == string1);
Тут скобки не нужны

2021-03-16 17:27 UTC, merged