Sem2hw2.2
ValentinaShvetsova/Homework pull request #35
Opened 2021-02-21 14:53 UTC by ValentinaShvetsova

2021-02-28 19:00 UTC, yurii-litvinov requested changes

2021-02-28 19:00 UTC, yurii-litvinov commented on SecondSemester/Homework2/PostfixCalculator/ArrayStack.cs
> +                Array.Resize(ref stackElements, stackElements.Length + 10);
Не-а, надо не `+ 10`, а `* 2`. Так у Вас каждый 10-й Push будет работать за линейное время, то есть если запушить n элементов подряд, то трудоёмкость будет порядка O(n^2) (пусть и с небольшой константой, но квадратичная). Если делать `* 2`, то при пуше n элементов потребуется всего log_2(n) линейных операций, то есть суммарная трудоёмкость будет `O(n * log(n))`, причём подавляющее большинство пушей будет копировать далеко не n элементов, так что можно вообще считать трудоёмкость линейной. Что существенно лучше.

2021-02-28 19:00 UTC, yurii-litvinov commented on SecondSemester/Homework2/PostfixCalculator/ArrayStack.cs
> +            stackElements[counter] = 0;
Вообще говоря, это не нужно. Вот если бы стек хранил ссылочные типы, заnull-ить ссылки было бы нужно, чтобы сборщик мусора из собрал, числа же хранятся по значению, так что ну и пусть себе лежат, затрём потом новыми.

2021-02-28 19:00 UTC, yurii-litvinov commented on SecondSemester/Homework2/PostfixCalculator/ArrayStack.cs
> +        public void Delete()
Лучше Clear(). Иначе все C++-ники будут думать, что оно удаляет стек, а оно его просто очищает

2021-02-28 19:00 UTC, yurii-litvinov commented on SecondSemester/Homework2/PostfixCalculator/Calculator.cs
> +    class SuperCalculator
Ни одного нестатического метода, так что сам класс должен быть static

2021-02-28 19:00 UTC, yurii-litvinov commented on SecondSemester/Homework2/PostfixCalculator/Calculator.cs
> +           foreach(char symbol in postfixExpression)
Надо пробел после foreach

2021-02-28 19:00 UTC, yurii-litvinov commented on SecondSemester/Homework2/PostfixCalculator/Calculator.cs
> +                }
Сложно :) Я бы побил выражение по пробелам с помощью string.Split и работал бы с каждой строкой как с числом или оператором. Ваш способ лучше тем, что обрабатывает `1+1`, но по условию всё разделено пробелами, и Ваш способ сложнее.

2021-02-28 19:00 UTC, yurii-litvinov commented on SecondSemester/Homework2/PostfixCalculator/Calculator.cs
> +                        if (stack.IsEmpty() || (symbol == '/' && topValue.CompareTo(0) == 0))
Это не решает проблему. В документации написано, что "Values must be identical to be considered equal. Particularly when floating-point values depend on multiple mathematical operations, it is common for them to lose precision and for their values to be nearly identical except for their least significant digits. Because of this, the return value of the CompareTo method at times may seem surprising". Это как раз то, из-за чего нельзя сравнивать double-ы через ==. Правильно сравнивать модуль разности с некоторой дельтой.

2021-02-28 19:00 UTC, yurii-litvinov commented on SecondSemester/Homework2/PostfixCalculator/Calculator.cs
> +           if (stack.IsEmpty())
Тут с отступом что-то не то

2021-02-28 19:00 UTC, yurii-litvinov commented on SecondSemester/Homework2/PostfixCalculator/Calculator.cs
> +            }
Это лучше было switch-ем

2021-02-28 19:00 UTC, yurii-litvinov commented on SecondSemester/Homework2/PostfixCalculator/IStack.cs
> +using System.Text;
Как много ненужных using-ов

2021-02-28 19:00 UTC, yurii-litvinov commented on SecondSemester/Homework2/PostfixCalculator/ListStack.cs
> +        }
Однострочные методы лучше писать через `=>`

2021-02-28 19:00 UTC, yurii-litvinov commented on SecondSemester/Homework2/PostfixCalculator/Program.cs
> +            IStack stack = choice switch
О, Вы знаете expression switch-и, тогда PerformOperation можно написать в три раза красивей

2021-02-28 19:00 UTC, yurii-litvinov commented on SecondSemester/Homework2/PostfixCalculator/Tests.cs
> +        }
Копипаст суть ересь. Воспользуйтесь магией полиморфизма, чтобы написать тест один раз и прогнать через него калькуляторы на двух разных стеках.

2021-03-02 12:10 UTC, yurii-litvinov requested changes

2021-03-02 12:10 UTC, yurii-litvinov commented on SecondSemester/Homework2/PostfixCalculator/Calculator.cs
> +
Лишняя пустая строчка

2021-03-02 12:10 UTC, yurii-litvinov commented on SecondSemester/Homework2/PostfixCalculator/ListStack.cs
> +            public StackElement Next;
Поля именуются со строчной всегда, свойства и методы --- с заглавной

2021-03-02 12:10 UTC, yurii-litvinov commented on SecondSemester/Homework2/PostfixCalculator/ListStack.cs
> +        }
И тоже однострочник, его тоже можно писать через `=>`

2021-03-02 12:10 UTC, yurii-litvinov commented on SecondSemester/Homework2/PostfixCalculator/Tests.cs
> +            IStack stack2 = new ListStack();
Фэйл :)

2021-03-02 12:10 UTC, yurii-litvinov commented on SecondSemester/Homework2/PostfixCalculator/Tests.cs
> +            return true;
Нельзя так писать

2021-03-02 12:10 UTC, yurii-litvinov commented on SecondSemester/Homework2/PostfixCalculator/Tests.cs
> +    }
Не-а, так у Вас Test2 и Test3 не проверяют поведение на разных стеках (а оно может отличаться, разные стеки теоретически по-разному детектят пустоту). Я больше хотел, чтобы каждый тест принимал стек в качестве параметра, и был бы метод, который создаёт список из двух разных стеков и для каждого элемента этого списка запускает все тесты.

2021-03-02 13:52 UTC, ValentinaShvetsova commented on SecondSemester/Homework2/PostfixCalculator/Tests.cs
> +            IStack stack2 = new ListStack();
Ой, случайно получилось

2021-03-03 15:17 UTC, yurii-litvinov approved these changes
Да, теперь всё ок, зачтена

2021-03-03 15:17 UTC, yurii-litvinov commented on SecondSemester/Homework2/PostfixCalculator/ListStack.cs
> +            public StackElement _next;
Не-а, Вы везде во всех остальных местах подчёркивание не используете, значит и тут не должны. Лучше было value и next, и в конструкторе this.value = value

2021-03-16 17:28 UTC, merged