2sem7.2
ValentinaShvetsova/Homework pull request #42
Opened 2021-03-31 15:13 UTC by ValentinaShvetsova

2021-05-02 08:09 UTC, yurii-litvinov requested changes
У меня оно выглядит как-то так:
![image](https://user-images.githubusercontent.com/706768/116806545-738aec00-ab36-11eb-9b70-8f973e6e1fea.png)

Может, стоит форму сделать побольше

2021-05-02 08:09 UTC, yurii-litvinov commented on SecondSemester/Homework7/Clock/ClockForm.cs
> +            private void timer1_Tick(object sender, EventArgs e)
Что-то с отступом не то

2021-05-02 08:09 UTC, yurii-litvinov commented on SecondSemester/Homework7/Clock/ClockForm.Designer.cs
> +            this.timer1.Interval = 1;
Одна миллисекунда? Это не лучшая идея, если мы хотим раз в секунду, в общем-то, время показывать. Тем более что одна миллисекунда --- это меньше разрешения системного таймера

2021-05-15 11:46 UTC, yurii-litvinov requested changes

2021-05-15 11:46 UTC, yurii-litvinov commented on SecondSemester/Homework7/Clock/ClockForm.Designer.cs
> +            this.timer1.Interval = 60;
Думаете, в секунде 60 миллисекунд? :)

2021-05-15 11:46 UTC, yurii-litvinov commented on SecondSemester/Homework7/Clock/ClockForm.Designer.cs
> +            this.ClientSize = new System.Drawing.Size(420, 420);
Не помогло:
![image](https://user-images.githubusercontent.com/706768/118359131-aac3b900-b58a-11eb-9e27-7f42afef1762.png)

Мне кажется, дело в https://github.com/ValentinaShvetsova/Homework/pull/42/files#diff-f50245bfb231973356ddb548219065e26480d92180647164021d014e22f75cd0R13 и слепой вере, что разрешение всех мониторов в мире совпадает в Вашим :)

2021-05-16 12:16 UTC, ValentinaShvetsova commented on SecondSemester/Homework7/Clock/ClockForm.Designer.cs
> +            this.ClientSize = new System.Drawing.Size(420, 420);
Просто у меня все выглядит замечательно, поэтому сложно понять, что может быть не так

2021-05-16 14:56 UTC, yurii-litvinov approved these changes
👍

2021-05-18 17:08 UTC, merged